services:
  sys-monitor:
    build: .
    container_name: linux-sys-monitor
    restart: always
    volumes:
      - .:/app
      - /var/log/auth.log:/var/log/auth.log:ro  # host SSH logs
      - /sys/class/thermal:/sys/class/thermal:ro # CPU temperature sensors
    ports:
      - "8080:8080"
    privileged: true # required for dmesg and Docker socket access
