name: Bash Static Analysis (ShellCheck)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck Analysis
        # On exclut SC2143 (style grep) et SC2162 (read sans -r, que nous utilisons pour le parsing multiple)
        run: shellcheck -e SC2143 -e SC2162 monitor.sh
